<a href="https://colab.research.google.com/github/asvaskamal403/syren/blob/master/python/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('===date 23 May===')

===date 23 May===


In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.22.4'

In [ ]:
# create 1 D array
# syntax : np.array([data1,data2....])
a = np.array([2,3,4,5,6])

In [ ]:
a

array([2, 3, 4, 5, 6])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
# creating 2 D array
# syntax : np.array([[d1,d2,d3],[d4,d5,d6],[d7,d8,d9]])
b= np.array([[1,1,1],[2,2,2],[3,3,3]])
b

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
# Assignment : creating 2 D array with 5 rows and 6 column.

In [ ]:
# printing the dimension form array
# syntax : array-var.ndim
a.ndim

1

In [ ]:
print('the dimensions of my matrix is : ', b.ndim)

the dimensions of my matrix is :  2


In [ ]:
# to print row and column form the given marix
# array.shape

In [ ]:
a.shape

(5,)

In [ ]:
b.shape

(3, 3)

In [ ]:
c= np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])
c

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [ ]:
c.shape

(4, 3)

In [ ]:
print('the rows : ', c.shape[0])

the rows :  4


In [ ]:
print('the columns : ', c.shape[1])

the columns :  3


In [ ]:
# if we want to total number of element
# arry.size
a.size

5

In [ ]:
b.size

9

In [ ]:
c.size

12

## **array Creation technique**

In [ ]:
# np.zeros()
# 1D
d = np.zeros(5)
d

array([0., 0., 0., 0., 0.])

In [ ]:
# 2d
d = np.zeros((4,5))
d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
d = np.zeros((4,5), dtype='int')
d

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
# 3d
d = np.zeros((3,2,3))
d

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
d = np.zeros((4,6,10))
d

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [ ]:
# np.ones()

In [ ]:
e = np.ones(5)
e

array([1., 1., 1., 1., 1.])

In [ ]:
e = np.ones((5,6))
e

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
e = np.ones((2,5,6))
e

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [ ]:
# if i need to create a matrix with no. 7
# fill -  > full
# np.full((row,col),num)
f = np.full((4,5),9)

In [ ]:
f

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [ ]:
f = np.full((2,4,5),9)

In [ ]:
f

array([[[9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9]],

       [[9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9]]])

In [ ]:
# random value : you need fraction values which is always less that 1
# syntax : np.random.random((r,c))
h= np.random.random((3,4))
h

array([[0.23552912, 0.47294317, 0.93331333, 0.37577513],
       [0.8831053 , 0.33830658, 0.85592831, 0.18103047],
       [0.76222822, 0.98431943, 0.6498927 , 0.07422772]])

In [ ]:
2+h

array([[2.23552912, 2.47294317, 2.93331333, 2.37577513],
       [2.8831053 , 2.33830658, 2.85592831, 2.18103047],
       [2.76222822, 2.98431943, 2.6498927 , 2.07422772]])

In [ ]:
6+h

array([[6.23552912, 6.47294317, 6.93331333, 6.37577513],
       [6.8831053 , 6.33830658, 6.85592831, 6.18103047],
       [6.76222822, 6.98431943, 6.6498927 , 6.07422772]])

In [ ]:
# approach 2 : you need integer random value between any range
# syntax : np.random.randint(low, high ,(r,c))
i = np.random.randint(20,40,(4,5))
i

array([[39, 24, 35, 24, 24],
       [34, 26, 35, 27, 27],
       [39, 25, 26, 24, 29],
       [24, 34, 25, 36, 22]])

In [ ]:
# create attendance (33-80) 100 students
i = np.random.randint(30,81,100)
i

array([31, 56, 51, 41, 38, 36, 75, 41, 60, 48, 79, 53, 76, 80, 48, 55, 61,
       80, 42, 56, 60, 70, 57, 78, 79, 58, 65, 75, 68, 72, 55, 69, 56, 47,
       66, 70, 62, 54, 36, 79, 42, 35, 65, 39, 56, 44, 72, 40, 41, 32, 51,
       64, 65, 58, 61, 41, 64, 45, 72, 42, 34, 32, 62, 30, 80, 64, 79, 60,
       38, 32, 59, 51, 60, 77, 34, 39, 65, 60, 31, 56, 33, 68, 54, 30, 47,
       57, 71, 68, 34, 50, 50, 43, 74, 31, 39, 34, 40, 55, 45, 77])

In [ ]:
# arange(start, end ,steps):
j = np.arange(1,10,1)
j

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
j = np.arange(1,10,0.4)
j

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. , 5.4, 5.8,
       6.2, 6.6, 7. , 7.4, 7.8, 8.2, 8.6, 9. , 9.4, 9.8])

In [ ]:
j = np.arange(1,10,0.1)
j

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [ ]:
# linsapce(start ,end , total number of element )
# Note : end point will get printed
g = np.linspace(1,10,10)
g

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
g = np.linspace(1,10,20)
g

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
g = np.linspace(1,10,100)
g

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [ ]:
# reshape((r,c))
# 1 D- > 2D
# 2D - > 1D

In [ ]:
# 1 D- > 2D

h = np.arange(1,25)
h

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
h.ndim

1

In [ ]:
# 1D - 2d
hh = h.reshape((6,4))
hh

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [ ]:
hh = h.reshape((12,2))
hh

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [ ]:
hh = h.reshape((2,12))
hh

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
# create 1 D array with 36 number 
# arrange these 36 element in 3 different ways 

In [ ]:
# 2d -> 2d 

In [ ]:
hi = np.random.randint(30,81,(6,4)).reshape(12,2)
hi

array([[33, 76],
       [34, 52],
       [65, 80],
       [52, 63],
       [57, 57],
       [70, 33],
       [34, 56],
       [53, 55],
       [41, 48],
       [55, 63],
       [60, 30],
       [36, 68]])

In [ ]:
# 2d - > 3d 
hi = np.random.randint(30,81,(6,4)).reshape(2,4,3)
hi

array([[[53, 62, 66],
        [34, 63, 61],
        [38, 45, 60],
        [55, 43, 38]],

       [[52, 35, 57],
        [44, 38, 48],
        [58, 79, 55],
        [61, 63, 68]]])

In [ ]:
# 2d - > 1d
# flatten() :'C' 
k = np.random.randint(30,81,(6,4))
k

array([[72, 34, 66, 35],
       [57, 47, 35, 53],
       [32, 48, 65, 44],
       [62, 61, 42, 76],
       [39, 67, 61, 80],
       [76, 69, 34, 60]])

In [ ]:
k.flatten()

array([72, 34, 66, 35, 57, 47, 35, 53, 32, 48, 65, 44, 62, 61, 42, 76, 39,
       67, 61, 80, 76, 69, 34, 60])

In [ ]:
# flatten() :'F' column major

In [ ]:
k.flatten('F')

array([72, 57, 32, 62, 39, 76, 34, 47, 48, 61, 67, 69, 66, 35, 65, 42, 61,
       34, 35, 53, 44, 76, 80, 60])

## **Math opeartion**

In [ ]:
# np.add(a1,a2)
a1= np.array([2,3,5,6,7,8])
a2 = np.array([7,6,5,4,3,1])
np.add(a1,a2)

array([ 9,  9, 10, 10, 10,  9])

In [ ]:
a1+a2

array([ 9,  9, 10, 10, 10,  9])

In [ ]:
# np.subtract(a1 ,a2 )
# -

# npmultiply(a1,a2)
# *


# np.divide(a1,a2)
# /

# np.power(a1,a2)
# **

# np.reminder(a1,a2)
# %

In [ ]:
# transpose 
a = np.arange(1,25).reshape(6,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [ ]:
a.T

array([[ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23],
       [ 4,  8, 12, 16, 20, 24]])

In [ ]:
a.T.T

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [ ]:
# max() 
# type1  : as on entire matix 
# type 2 : as row wise (axis =1)
# type 3 : as row wise (axis =0)
c= np.random.randint(10,99,(6,4))
c

array([[28, 86, 30, 37],
       [58, 34, 97, 38],
       [69, 31, 48, 74],
       [56, 28, 75, 93],
       [67, 42, 86, 45],
       [85, 92, 27, 12]])

In [ ]:
# on entire matrix
c.max()

97

In [ ]:
# row wise
c.max(axis =1)

array([86, 97, 74, 93, 86, 92])

In [ ]:
# col wise
c.max(axis =0)

array([85, 92, 97, 93])

In [ ]:
# assignment : min()
# assignment : sum()


In [ ]:
c

array([[28, 86, 30, 37],
       [58, 34, 97, 38],
       [69, 31, 48, 74],
       [56, 28, 75, 93],
       [67, 42, 86, 45],
       [85, 92, 27, 12]])

In [ ]:
# sorting
np.sort(c , axis = None)

array([12, 27, 28, 28, 30, 31, 34, 37, 38, 42, 45, 48, 56, 58, 67, 69, 74,
       75, 85, 86, 86, 92, 93, 97])

In [ ]:
# row sorting
np.sort(c , axis = 1)

array([[28, 30, 37, 86],
       [34, 38, 58, 97],
       [31, 48, 69, 74],
       [28, 56, 75, 93],
       [42, 45, 67, 86],
       [12, 27, 85, 92]])

In [ ]:
# col sorting
np.sort(c , axis = 0)

array([[28, 28, 27, 12],
       [56, 31, 30, 37],
       [58, 34, 48, 38],
       [67, 42, 75, 45],
       [69, 86, 86, 74],
       [85, 92, 97, 93]])

## **Numpy function for sats**

In [ ]:
# np.mean()
# np.median() #==== too much time
# np.std()
# np.var()

In [ ]:
data1=np.array([600,470,170,430,300])

In [ ]:
np.mean(data1)

394.0

In [ ]:
np.std(data1)

147.32277488562318

In [ ]:
np.var(data1)

21704.0

## **Array slicing**

In [ ]:
a = np.random.randint(20,40,(6,7))
a

array([[29, 23, 22, 25, 20, 22, 22],
       [27, 32, 24, 22, 25, 22, 38],
       [36, 21, 20, 27, 31, 38, 32],
       [30, 25, 25, 27, 20, 26, 31],
       [31, 29, 28, 35, 25, 38, 25],
       [33, 39, 27, 39, 22, 20, 27]])

In [ ]:
a[1:5,2:6]

array([[24, 22, 25, 22],
       [20, 27, 31, 38],
       [25, 27, 20, 26],
       [28, 35, 25, 38]])

In [ ]:
a[5::,3:4:]

array([[39]])

In [ ]:
a[5,3]

39

In [ ]:
a[::2,::2]

array([[29, 22, 20, 22],
       [36, 20, 31, 32],
       [31, 28, 25, 25]])

In [ ]:
a[::2,::]

array([[29, 23, 22, 25, 20, 22, 22],
       [36, 21, 20, 27, 31, 38, 32],
       [31, 29, 28, 35, 25, 38, 25]])

In [ ]:
a[::,::]

array([[29, 23, 22, 25, 20, 22, 22],
       [27, 32, 24, 22, 25, 22, 38],
       [36, 21, 20, 27, 31, 38, 32],
       [30, 25, 25, 27, 20, 26, 31],
       [31, 29, 28, 35, 25, 38, 25],
       [33, 39, 27, 39, 22, 20, 27]])

In [ ]:
# syntax 
# arry-var[row start:row end :row step , col start:col end : col step ]

## **Matrix Mul**

In [ ]:
# dot product():
# r1 x c1   r2 x c2
# so the condition c1 == r2
# url : https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [ ]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[7,8],[9,10],[11,12]])

In [ ]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
m2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
m1.dot(m2)

array([[ 58,  64],
       [139, 154]])